version: '3.8'
services:
  web-app:
    image: pattern_finder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - redis-cache
      - mongo-db
    environment:
      - spring.data.redis.url=redis://redis-cache:6379/redis
      - spring.data.mongodb.uri=mongodb://mongo-db:27017/mongo

  redis-cache:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

  mongo-db:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
